"""contribution assets and uploads

Revision ID: 1430af1c7931
Revises: da191d3541f1
Create Date: 2026-07-09 09:55:54.117226
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1430af1c7931'
down_revision: Union[str, Sequence[str], None] = 'da191d3541f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_assets',
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=30), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_contribution_assets_contribution_id_contributions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_contribution_assets_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contribution_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_contribution_assets_storage_key'))
    )
    op.create_index(op.f('ix_contribution_assets_contribution_id'), 'contribution_assets', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_contribution_assets_media_type'), 'contribution_assets', ['media_type'], unique=False)
    op.create_index(op.f('ix_contribution_assets_status'), 'contribution_assets', ['status'], unique=False)
    op.create_index(op.f('ix_contribution_assets_uploaded_by'), 'contribution_assets', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_assets_uploaded_by'), table_name='contribution_assets')
    op.drop_index(op.f('ix_contribution_assets_status'), table_name='contribution_assets')
    op.drop_index(op.f('ix_contribution_assets_media_type'), table_name='contribution_assets')
    op.drop_index(op.f('ix_contribution_assets_contribution_id'), table_name='contribution_assets')
    op.drop_table('contribution_assets')
    # ### end Alembic commands ###
