"""reviews rewards annotations synthetic datasets

Revision ID: 53f49f7cfa15
Revises: 1430af1c7931
Create Date: 2026-07-09 10:20:41.738334
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53f49f7cfa15'
down_revision: Union[str, Sequence[str], None] = '1430af1c7931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_datasets_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('name', name=op.f('uq_datasets_name'))
    )
    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pending_coins', sa.Integer(), nullable=False),
    sa.Column('earned_coins', sa.Integer(), nullable=False),
    sa.Column('redeemed_coins', sa.Integer(), nullable=False),
    sa.Column('expired_coins', sa.Integer(), nullable=False),
    sa.Column('total_lifetime_coins', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets'))
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('dataset_exports',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('export_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_dataset_exports_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_exports_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_exports'))
    )
    op.create_index(op.f('ix_dataset_exports_dataset_id'), 'dataset_exports', ['dataset_id'], unique=False)
    op.create_table('synthetic_examples',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('example_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=True),
    sa.Column('synthetic_source_model', sa.String(length=160), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_synthetic_examples_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_synthetic_examples_language_id_languages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_synthetic_examples'))
    )
    op.create_index(op.f('ix_synthetic_examples_example_type'), 'synthetic_examples', ['example_type'], unique=False)
    op.create_index(op.f('ix_synthetic_examples_language_id'), 'synthetic_examples', ['language_id'], unique=False)
    op.create_table('coin_transactions',
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('contribution_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_coin_transactions_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_coin_transactions_contribution_id_contributions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], name=op.f('fk_coin_transactions_wallet_id_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coin_transactions'))
    )
    op.create_index(op.f('ix_coin_transactions_contribution_id'), 'coin_transactions', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_coin_transactions_wallet_id'), 'coin_transactions', ['wallet_id'], unique=False)
    op.create_table('dataset_items',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_dataset_items_contribution_id_contributions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_items_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_items'))
    )
    op.create_index(op.f('ix_dataset_items_contribution_id'), 'dataset_items', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_dataset_items_dataset_id'), 'dataset_items', ['dataset_id'], unique=False)
    op.create_table('reviews',
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_reviews_contribution_id_contributions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_action'), 'reviews', ['action'], unique=False)
    op.create_index(op.f('ix_reviews_contribution_id'), 'reviews', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_table('image_annotations',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('label_name', sa.String(length=160), nullable=False),
    sa.Column('label_language_id', sa.Uuid(), nullable=True),
    sa.Column('label_translation', sa.String(length=160), nullable=True),
    sa.Column('annotation_type', sa.String(length=30), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=True),
    sa.Column('y_min', sa.Float(), nullable=True),
    sa.Column('x_max', sa.Float(), nullable=True),
    sa.Column('y_max', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['contribution_assets.id'], name=op.f('fk_image_annotations_asset_id_contribution_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_image_annotations_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['label_language_id'], ['languages.id'], name=op.f('fk_image_annotations_label_language_id_languages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_annotations'))
    )
    op.create_index(op.f('ix_image_annotations_asset_id'), 'image_annotations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_image_annotations_created_by'), 'image_annotations', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_annotations_created_by'), table_name='image_annotations')
    op.drop_index(op.f('ix_image_annotations_asset_id'), table_name='image_annotations')
    op.drop_table('image_annotations')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_contribution_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_action'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_dataset_items_dataset_id'), table_name='dataset_items')
    op.drop_index(op.f('ix_dataset_items_contribution_id'), table_name='dataset_items')
    op.drop_table('dataset_items')
    op.drop_index(op.f('ix_coin_transactions_wallet_id'), table_name='coin_transactions')
    op.drop_index(op.f('ix_coin_transactions_contribution_id'), table_name='coin_transactions')
    op.drop_table('coin_transactions')
    op.drop_index(op.f('ix_synthetic_examples_language_id'), table_name='synthetic_examples')
    op.drop_index(op.f('ix_synthetic_examples_example_type'), table_name='synthetic_examples')
    op.drop_table('synthetic_examples')
    op.drop_index(op.f('ix_dataset_exports_dataset_id'), table_name='dataset_exports')
    op.drop_table('dataset_exports')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
