"""contribution and translation workflow

Revision ID: b7472d55d698
Revises: c3577a185615
Create Date: 2026-07-09 09:43:23.423524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7472d55d698'
down_revision: Union[str, Sequence[str], None] = 'c3577a185615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('contributions',
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('contribution_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('dialect_id', sa.Uuid(), nullable=True),
    sa.Column('target_language_id', sa.Uuid(), nullable=True),
    sa.Column('target_dialect_id', sa.Uuid(), nullable=True),
    sa.Column('speech_community_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=120), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('license_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_contributions_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_contributions_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], name=op.f('fk_contributions_dialect_id_dialects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_contributions_language_id_languages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['speech_community_id'], ['speech_communities.id'], name=op.f('fk_contributions_speech_community_id_speech_communities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_dialect_id'], ['dialects.id'], name=op.f('fk_contributions_target_dialect_id_dialects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], name=op.f('fk_contributions_target_language_id_languages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contributions'))
    )
    op.create_index(op.f('ix_contributions_author_id'), 'contributions', ['author_id'], unique=False)
    op.create_index(op.f('ix_contributions_category_id'), 'contributions', ['category_id'], unique=False)
    op.create_index(op.f('ix_contributions_contribution_type'), 'contributions', ['contribution_type'], unique=False)
    op.create_index(op.f('ix_contributions_language_id'), 'contributions', ['language_id'], unique=False)
    op.create_index(op.f('ix_contributions_status'), 'contributions', ['status'], unique=False)
    op.create_index(op.f('ix_contributions_target_language_id'), 'contributions', ['target_language_id'], unique=False)
    op.create_table('consents',
    sa.Column('contributor_id', sa.Uuid(), nullable=False),
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.Column('consent_version', sa.String(length=30), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('use_for_ai_training', sa.Boolean(), nullable=False),
    sa.Column('use_for_research', sa.Boolean(), nullable=False),
    sa.Column('use_for_commercial', sa.Boolean(), nullable=False),
    sa.Column('allow_open_release', sa.Boolean(), nullable=False),
    sa.Column('allow_attribution', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_consents_contribution_id_contributions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], name=op.f('fk_consents_contributor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_contribution_id'), 'consents', ['contribution_id'], unique=True)
    op.create_index(op.f('ix_consents_contributor_id'), 'consents', ['contributor_id'], unique=False)
    op.create_table('translation_pairs',
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_translation_pairs_contribution_id_contributions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_pairs'))
    )
    op.create_index(op.f('ix_translation_pairs_contribution_id'), 'translation_pairs', ['contribution_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_pairs_contribution_id'), table_name='translation_pairs')
    op.drop_table('translation_pairs')
    op.drop_index(op.f('ix_consents_contributor_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_contribution_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_contributions_target_language_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_status'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_language_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_contribution_type'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_category_id'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_author_id'), table_name='contributions')
    op.drop_table('contributions')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
