"""identity and language taxonomy

Revision ID: c3577a185615
Revises:
Create Date: 2026-07-09 09:36:34.708483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c3577a185615'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_groups',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_language_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_language_groups_name'))
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('languages',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('local_name', sa.String(length=120), nullable=True),
    sa.Column('iso_code', sa.String(length=12), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['language_groups.id'], name=op.f('fk_languages_group_id_language_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('name', 'group_id', name=op.f('uq_languages_name'))
    )
    op.create_index(op.f('ix_languages_iso_code'), 'languages', ['iso_code'], unique=False)
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    op.create_table('dialects',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('local_name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_dialects_language_id_languages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialects')),
    sa.UniqueConstraint('name', 'language_id', name=op.f('uq_dialects_name'))
    )
    op.create_index(op.f('ix_dialects_language_id'), 'dialects', ['language_id'], unique=False)
    op.create_table('speech_communities',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=True),
    sa.Column('dialect_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], name=op.f('fk_speech_communities_dialect_id_dialects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_speech_communities_language_id_languages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speech_communities'))
    )
    op.create_index(op.f('ix_speech_communities_district'), 'speech_communities', ['district'], unique=False)
    op.create_index(op.f('ix_speech_communities_name'), 'speech_communities', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speech_communities_name'), table_name='speech_communities')
    op.drop_index(op.f('ix_speech_communities_district'), table_name='speech_communities')
    op.drop_table('speech_communities')
    op.drop_index(op.f('ix_dialects_language_id'), table_name='dialects')
    op.drop_table('dialects')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_index(op.f('ix_languages_iso_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('language_groups')
    # ### end Alembic commands ###
