"""conversation threads and turns

Revision ID: da191d3541f1
Revises: b7472d55d698
Create Date: 2026-07-09 09:48:36.093629
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da191d3541f1'
down_revision: Union[str, Sequence[str], None] = 'b7472d55d698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_threads',
    sa.Column('contribution_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_count', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], name=op.f('fk_conversation_threads_contribution_id_contributions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_threads'))
    )
    op.create_index(op.f('ix_conversation_threads_contribution_id'), 'conversation_threads', ['contribution_id'], unique=True)
    op.create_table('conversation_turns',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=80), nullable=False),
    sa.Column('speaker_role', sa.String(length=80), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation_threads.id'], name=op.f('fk_conversation_turns_conversation_id_conversation_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns')),
    sa.UniqueConstraint('conversation_id', 'turn_order', name=op.f('uq_conversation_turns_conversation_id'))
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_conversation_threads_contribution_id'), table_name='conversation_threads')
    op.drop_table('conversation_threads')
    # ### end Alembic commands ###
